### PR TITLE
Create french-toast.md

### PR DESCRIPTION
**Pull request by caleb-m**
My french toast is the best french toast

@githubteacher, plz confirm

### CODE REVIEW

**Comment by edusis** [comment]
a comment

**Comment by matthewmccullough** [comment]
@caleb-m In your branch, in your fork, could you rename this file to say, `caleb-french-toast.md` and that way it won't collide with Joshua's file.  Just click the pencil icon to edit the file and then type a new name where the filename is listed and commit.

**Comment by caleb-m** [comment]
@matthewmccullough changes made

**Comment by matthewmccullough** [comment]
@caleb-m I've shipped it! :shipit:

**Comment by caleb-m** [comment]
Huzzah! :8ball:

**Pull request merged**
