### PR TITLE
First stab at quest.

### PR DESCRIPTION
**Pull request by githubteacher**
Not ready to go, but worth a look by @mstanleyjones and @max-webster

### CODE REVIEW

**Comment by aschauer** [comment]
Looks good, but is it spicy enough?

**Comment by githubteacher** [comment]
@bernars Can I help here?

**Comment by smarvin** [comment]
Make sure you run it by "That Guy."

**Comment by briandburton** [comment]
No one likes to be "That Guy."

**Comment by CrisMorris95120** [comment]
That Guy says try again.

**Comment by briandburton** [comment]
I think Cris's job is to be "That Guy."

**Pull request merged**
