### PR TITLE
Create french-toast.md

### PR DESCRIPTION
**Pull request by pschloss**
I think your recipe needs some nutmeg

### CODE REVIEW

**Comment by pschloss** [comment]
@githubteacher can you review this new recipe?

**Comment by githubteacher** [comment]
:+1:

**Comment by matthewmccullough** [comment]
@pschloss In your branch, in your fork, could you rename this file to say, psch-french-toast.md and that way it won't collide with Joshua's file. Just click the pencil icon to edit the file and then type a new name where the filename is listed and commit.

**Comment by pschloss** [comment]
done - thanks - can you check it out now? @matthewmccullough

**Comment by matthewmccullough** [comment]
Perfect. Shipped it!

**Pull request merged**
