### PR TITLE
Add recipe for french toast

### PR DESCRIPTION
**Pull request by jerryo510**
I think we should have a recipe for french toast. What do you think?

### CODE REVIEW

**Comment by jerryo510** [comment]
Can you review this new recipe?

**Comment by chmorris9795** [comment]
sounds excellent

**Comment by matthewmccullough** [comment]
@jerryo510 In your branch, in your fork, could you rename this file to say, caleb-french-toast.md and that way it won't collide with Joshua's file. Just click the pencil icon to edit the file and then type a new name where the filename is listed and commit.

**Comment by jerryo510** [comment]
I can’t seem to edit the post. It says “You must be on a branch to make or
propose changes to this file”



Thank you,



*Jerry Oshiro*

*Rate Highway, Inc.*

[image: cid:image003.png@01CEC8EB.FFE12CE0]

949.238.6438 direct

949.614.0751 x706 office

949.238.6438 fax



Rate-Highway Email Confidentiality Statement:



This email and any files transmitted with it are confidential and intended
solely for the addressee(s).  If you are not the intended recipient you
should not disseminate; distribute; copy or alter this email. If you have
received this message in error, please immediately notify the sender by
reply e-mail and delete this message from your computer.  Although we have
taken steps to ensure that this e-mail and attachments are free from any
virus, we advise that in keeping with good computing practice the recipient
should ensure they are actually virus free



*From:* Matthew McCullough [mailto:notifications@github.com]
*Sent:* Tuesday, January 20, 2015 11:26 AM
*To:* githubschool/recipes
*Cc:* jerryo510
*Subject:* Re: [recipes] Add recipe for french toast (#205)



@jerryo510 <https://github.com/jerryo510> In your branch, in your fork,
could you rename this file to say, caleb-french-toast.md and that way it
won't collide with Joshua's file. Just click the pencil icon to edit the
file and then type a new name where the filename is listed and commit.

—
Reply to this email directly or view it on GitHub
<https://github.com/githubschool/recipes/pull/205#issuecomment-70715578>.

**Comment by matthewmccullough** [comment]
image

@jerryo510 From the https://github.com/githubschool/recipes/pull/205 page, you should be able to, as long as logged in as jerryo510, be able to click that pencil from the pull request's last tab.

**Comment by jerryo510** [comment]
I found it through another route, but your way was faster. Thank you!



Thank you,



*Jerry Oshiro*

*Rate Highway, Inc.*

[image: cid:image003.png@01CEC8EB.FFE12CE0]

949.238.6438 direct

949.614.0751 x706 office

949.238.6438 fax



Rate-Highway Email Confidentiality Statement:



This email and any files transmitted with it are confidential and intended
solely for the addressee(s).  If you are not the intended recipient you
should not disseminate; distribute; copy or alter this email. If you have
received this message in error, please immediately notify the sender by
reply e-mail and delete this message from your computer.  Although we have
taken steps to ensure that this e-mail and attachments are free from any
virus, we advise that in keeping with good computing practice the recipient
should ensure they are actually virus free



*From:* Matthew McCullough [mailto:notifications@github.com]
*Sent:* Tuesday, January 20, 2015 11:45 AM
*To:* githubschool/recipes
*Cc:* jerryo510
*Subject:* Re: [recipes] Add recipe for french toast (#205)



[image: image]
<https://cloud.githubusercontent.com/assets/24734/5824469/a6a97060-a099-11e4-8334-f5af7999da21.png>

@jerryo510 <https://github.com/jerryo510> From the #205
<https://github.com/githubschool/recipes/pull/205> page, you should be able
to, as long as logged in as jerryo510, be able to click that pencil from
the pull request's last tab.

—
Reply to this email directly or view it on GitHub
<https://github.com/githubschool/recipes/pull/205#issuecomment-70719134>.

**Comment by matthewmccullough** [comment]
Perfect. :shipit: !

**Pull request merged**
