### PR TITLE
Hot Sauce addition

### PR DESCRIPTION
**Pull request by pauldb**
* Much hotter!

### CODE REVIEW

**Comment by githubteacher** [comment]
I like it, but should you choose a name brand of hot sauce? Edit that up and we're good to go!

**Comment by pauldb** [comment]
@githubteacher ok I'll do it

**Comment by briandburton** [comment]
@pauldb I recommend Satan's Blood

http://ep.yimg.com/ca/I/hotsauceworld_2253_10942343

**Comment by mcudahy** [comment]
@pauldb Your father would be proud.

**Comment by max-webster** [comment]
"Ass in the Tub" http://www.hotsauce.com/Ass-In-The-Tub-Hot-Sauce-p/1202.htm

**Pull request merged**
