### PR TITLE
Add red velvet cake recipe

### PR DESCRIPTION
**Pull request by githubstudent**

### CODE REVIEW

**Comment by githubteacher** [comment]
This recipe looks delicious, but I don't believe it meets our contribution guidelines.

**Comment by githubstudent** [comment]
Thank you for that link.  I have updated the formatting to meet the guidelines. :+1:

**Comment by githubteacher** [comment]
Those changes look fantastic @githubstudent.  Looking back at this recipe, I believe it may be from a copyrighted source.

cc: @githubschool/legal-department - Is it okay for us to publish this?

**Comment by githubteacher** [comment]
Based on offline conversations with @githubschool/legal-department, it looks like we are not able to publish this particular recipe on our site.  We appreciate your contribution though @githubstudent.  :smiley:

:-1: :frowning:

**Comment by githubstudent** [comment]
I completely understand the copyright concerns @githubteacher.  If I were to tweak the recipe with my own ingredients and instructions, would it be publishable?

**Pull request closed without merging**
